CREATE TABLE "user" (
	"ID"	NUMBER(19)		NOT NULL,
	"EMAIL"	VARCHAR2(45)		NULL,
	"PASSWORD"	VARCHAR2(50)		NULL,
	"NAME"	VARCHAR2(10)		NULL,
	"GENDER"	CHAR(1) CHECK(  GENDER IN ('M', 'F'))		NULL,
	"CREATED_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL,
	"DELETE_TIME"	DATE		NULL
);

COMMENT ON COLUMN "user"."ID" IS '시퀀스 적용';

CREATE TABLE "user_info" (
	"USER_ID"	NUMBER(19)		NOT NULL,
	"HEIGHT"	FLOAT		NULL,
	"WEIGHT"	FLOAT		NULL,
	"BODY_FAT"	FLOAT		NULL,
	"MUSCLE_MASS"	FLOAT		NULL,
	"KCAL_START"	FLOAT		NULL,
	"KCAL"	FLOAT		NULL,
	"KCAL_WEEKLY"	FLOAT		NULL,
	"WEIGHT_GOAL"	FLOAT		NULL,
	"WEIGHT_LOSS"	FLOAT		NULL,
	"CREATED_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

COMMENT ON COLUMN "user_info"."USER_ID" IS '시퀀스 적용';

CREATE TABLE "user_activity" (
	"ID"	NUMBER(19)		NOT NULL,
	"ACTIVITY"	VARCHAR2(50)		NOT NULL,
	"ACTIVITY_TIME"	NUMBER	DEFAULT 1	NOT NULL,
	"CREATED_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL,
	"ACTIVITY_ID"	NUMBER(19)		NOT NULL,
	"USER_ID"	NUMBER(19)		NOT NULL
);

COMMENT ON COLUMN "user_activity"."USER_ID" IS '시퀀스 적용';

CREATE TABLE "activity" (
	"ID"	NUMBER(19)		NOT NULL,
	"INTENSITY"	FLOAT		NULL,
	"ACTIVITY"	VARCHAR2(50)		NULL,
	"CREATED_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

CREATE TABLE "user_diet" (
	"ID"	NUMBER(19)		NOT NULL,
	"QUANTITY"	FLOAT		NULL,
	"CREATED_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL,
	"TIME"	NUMBER(3)		NULL,
	"USER_ID"	NUMBER(19)		NOT NULL,
	"DIET_ID"	NUMBER(19)		NOT NULL,
	"DATE"	DATE		NULL
);

COMMENT ON COLUMN "user_diet"."TIME" IS '0 : 아침
1 : 점심
2 : 저녁
3 : 간식';

COMMENT ON COLUMN "user_diet"."USER_ID" IS '시퀀스 적용';

CREATE TABLE "diet" (
	"ID"	NUMBER(19)		NOT NULL,
	"AMOUNT"	FLOAT		NULL,
	"CARBOHYDRATE"	FLOAT		NULL,
	"PROTEIN"	FLOAT		NULL,
	"FAT"	FLOAT		NULL,
	"TITLE"	VARCHAR2(50)		NULL,
	"CREATED_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

CREATE TABLE "USER_DAILY_RECORD" (
	"ID"	NUMBER(19)		NOT NULL,
	"DATE"	DATE		NULL,
	"WEIGHT"	FLOAT		NULL,
	"BODY_FAT"	FLOAT		NULL,
	"MUSCLE_MASS"	FLOAT		NULL,
	"CREATED_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL,
	"ID2"	NUMBER(19)		NOT NULL
);

COMMENT ON COLUMN "USER_DAILY_RECORD"."ID2" IS '시퀀스 적용';

ALTER TABLE "user" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "user_info" ADD CONSTRAINT "PK_USER_INFO" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "user_activity" ADD CONSTRAINT "PK_USER_ACTIVITY" PRIMARY KEY (
	"ID"
);

ALTER TABLE "activity" ADD CONSTRAINT "PK_ACTIVITY" PRIMARY KEY (
	"ID"
);

ALTER TABLE "user_diet" ADD CONSTRAINT "PK_USER_DIET" PRIMARY KEY (
	"ID"
);

ALTER TABLE "diet" ADD CONSTRAINT "PK_DIET" PRIMARY KEY (
	"ID"
);

ALTER TABLE "USER_DAILY_RECORD" ADD CONSTRAINT "PK_USER_DAILY_RECORD" PRIMARY KEY (
	"ID"
);

ALTER TABLE "user_info" ADD CONSTRAINT "FK_user_TO_user_info_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "user" (
	"ID"
);

